[package]
name = "generative-pixel-art"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
image = "0.25.6"
rand = "0.9.1"
rayon = "1.10.0"
